BEGIN TRANSACTION;
CREATE TABLE "USERS" ("ID" INTEGER PRIMARY KEY NOT NULL UNIQUE, "NAME" TEXT NOT NULL UNIQUE, "PASSWORD_SHA512" TEXT NOT NULL, "GROUPS" TEXT NOT NULL DEFAULT '');
INSERT INTO "USERS" ("NAME", "PASSWORD_SHA512", "GROUPS") VALUES ('root', 'cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e', 'root');
CREATE TABLE "SHARES" ("ID" INTEGER PRIMARY KEY NOT NULL UNIQUE, "NAME" TEXT NOT NULL UNIQUE, "PATH" TEXT NOT NULL, "GROUPS_VISIBLE" TEXT NOT NULL, "GROUPS_ACCESS_FILES" TEXT NOT NULL, "GROUPS_MODIFY_FILES" TEXT NOT NULL);
COMMIT TRANSACTION;


-- used for development, always rolled back
BEGIN TRANSACTION;
CREATE TABLE "LOG" ("ID" INTEGER PRIMARY KEY NOT NULL UNIQUE, "USERNAME" TEXT NOT NULL, "TIME" INTEGER NOT NULL, "REQUEST_TYPE" TEXT NOT NULL DEFAULT 'unknown', "FULL_PATH1" TEXT NOT NULL DEFAULT '', "FULL_PATH2" TEXT DEFAULT NULL);
-- request types: 'list', 'stream', 'download', 'upload', 'move', 'copy', 'delete'
ROLLBACK TRANSACTION;
